steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', '/workspace/cloud', 'gs://mc-staging-bucket/cloud']
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', '/workspace/server', 'gs://mc-staging-bucket/server']