
["Weakness Effect"]
	#The maximum of the total amount of items a player can eat before receiving the weakness effect. A value of -1 disables this feature.
	#Range: -1 ~ 1280
	maxItemUsesPerDayTotal = -1
	#The duration of the weakness effect in seconds when eating too much of an item.
	#Range: 1 ~ 3600
	weaknessDurationSeconds = 45
	#The maximum amount of an item a player can eat before receiving the weakness effect. A value of -1 disables this feature.
	#Range: -1 ~ 1280
	maxItemUsesPerDaySingleItem = 16

["Glow Effect"]
	#For the glow effect, the radius in blocks around the player of entities affected.
	#Range: 1 ~ 128
	glowEntitiesAroundAffectedRadiusBlocks = 32
	#When eating glowstone, the duration in seconds of how long entities around should be glowing with an outline. A value of 0 disables the item use.
	#Range: 0 ~ 3600
	glowEntityDurationSeconds = 20

["Other Effects"]
	#After eating some sugar, the duration in seconds of the speed effect the player receives. A value of 0 disables the item use.
	#Range: 0 ~ 3600
	sugarSpeedDurationSeconds = 15
	#After eating blaze powder, the duration in seconds of the strength effect the player receives. A value of 0 disables the item use.
	#Range: 0 ~ 3600
	blazePowderStrengthDurationSeconds = 15
	#After eating magma cream, the duration in seconds of the fire resistance effect the player receives. A value of 0 disables the item use.
	#Range: 0 ~ 3600
	magmaCreamFireResistanceDurationSeconds = 15

